# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170425_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='activacion_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
