# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_perfil_activacion_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='olvido_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
