# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_perfil_moderador'),
        ('login', '0004_perfil_olvido_token'),
    ]

    operations = [
    ]
