# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_perfil_moderador'),
        ('login', '0004_perfil_olvido_token'),
    ]

    operations = [
    ]
