# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_merge_20170531_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fechaBaja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
