# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_merge_20170530_2308'),
        ('login', '0007_perfil_fechabaja'),
    ]

    operations = [
    ]
