# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_merge_20170602_0005'),
        ('login', '0008_merge_20170602_0006'),
    ]

    operations = [
    ]
