# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_merge_20170602_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fechaBaja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
