# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cabSubasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precioBase', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fechaAlta', models.DateTimeField(auto_now=True, null=True)),
                ('fechaBaja', models.DateTimeField(auto_now=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detSubasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorOferta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fechaOferta', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('idSubasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.cabSubasta')),
                ('usuarioComprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='cabsubasta',
            name='idCalificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.calificacion'),
        ),
        migrations.AddField(
            model_name='cabsubasta',
            name='idSubcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.subCategoria'),
        ),
        migrations.AddField(
            model_name='cabsubasta',
            name='usuarioVendedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
