# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaAlta', models.DateTimeField(auto_now=True, null=True)),
                ('idUsuarioComprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fechaBaja', models.DateTimeField(auto_now=True, null=True)),
                ('fechaAlta', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('URL', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaBaja', models.DateTimeField(auto_now=True, null=True)),
                ('fechaAlta', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorOferta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fechaOferta', models.DateTimeField(auto_now=True, null=True)),
                ('ganador', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fechaBaja', models.DateTimeField(auto_now=True, null=True)),
                ('fechaAlta', models.DateTimeField(auto_now=True, null=True)),
                ('idComentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Comentarios')),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subastas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, null=True)),
                ('precioBase', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fechaAlta', models.DateTimeField(auto_now=True, null=True)),
                ('fechaBaja', models.DateTimeField(auto_now=True, null=True)),
                ('fechaFin', models.DateTimeField(auto_now=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('idCalificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Calificaciones')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='categoria',
            new_name='Categorias',
        ),
        migrations.RemoveField(
            model_name='cabsubasta',
            name='idCalificacion',
        ),
        migrations.RemoveField(
            model_name='cabsubasta',
            name='idSubcategoria',
        ),
        migrations.RemoveField(
            model_name='cabsubasta',
            name='usuarioVendedor',
        ),
        migrations.RemoveField(
            model_name='detsubasta',
            name='idSubasta',
        ),
        migrations.RemoveField(
            model_name='detsubasta',
            name='usuarioComprador',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='idCategoria',
        ),
        migrations.DeleteModel(
            name='cabSubasta',
        ),
        migrations.DeleteModel(
            name='calificacion',
        ),
        migrations.DeleteModel(
            name='detSubasta',
        ),
        migrations.DeleteModel(
            name='subCategoria',
        ),
        migrations.AddField(
            model_name='subcategorias',
            name='idCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Categorias'),
        ),
        migrations.AddField(
            model_name='subastas',
            name='idSubcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.SubCategorias'),
        ),
        migrations.AddField(
            model_name='subastas',
            name='idUsuarioVendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subastas',
            name='usuarioVendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Categorias'),
        ),
        migrations.AddField(
            model_name='ofertas',
            name='idSubasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Subastas'),
        ),
        migrations.AddField(
            model_name='ofertas',
            name='usuarioComprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes',
            name='idSubasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Subastas'),
        ),
        migrations.AddField(
            model_name='likes',
            name='idUsuarioVendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='idSubasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.Subastas'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='idSubasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Subastas'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='idUsuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
