# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_auto_20170425_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='subastas',
            name='idCalificacion',
        ),
        migrations.RemoveField(
            model_name='subastas',
            name='idSubcategoria',
        ),
        migrations.RemoveField(
            model_name='subastas',
            name='usuarioVendedor',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
