# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20170427_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='detalle',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subastas',
            name='idCalificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Calificaciones'),
        ),
        migrations.AddField(
            model_name='subastas',
            name='idSubcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.SubCategorias'),
        ),
    ]
