# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_auto_20170427_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='subastas',
            name='idCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Categorias'),
        ),
    ]
