# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_subastas_idcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='idSubasta',
        ),
        migrations.AddField(
            model_name='subastas',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='subastas',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='subastas',
            name='magen2',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
