# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0006_auto_20170427_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subastas',
            old_name='magen2',
            new_name='imagen3',
        ),
    ]
