# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_auto_20170428_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='subastas',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
