# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_subastas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subastas',
            name='fechaFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='imagen1',
            field=models.ImageField(default='sitio/static/img', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='titulo',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
