# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import sitio.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_auto_20170503_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subastas',
            name='fechaBaja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='imagen1',
            field=models.ImageField(default='', upload_to=sitio.models.upload_to_subastas),
        ),
    ]
