# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_auto_20170503_1751'),
        ('sitio', '0010_auto_20170508_2127'),
    ]

    operations = [
    ]
