# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_merge_20170508_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subastas',
            name='fechaFin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
