# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0012_auto_20170508_2209'),
        ('sitio', '0012_auto_20170508_2215'),
    ]

    operations = [
    ]
