# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 01:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sitio.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0013_auto_20170511_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='idSubasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Subastas'),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='usuarioComprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ofertas',
            name='valorOferta',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='detalle',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='idCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Categorias'),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='imagenA',
            field=models.ImageField(default='', null=True, upload_to=sitio.models.upload_to_subastas),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='imagenB',
            field=models.ImageField(blank=True, null=True, upload_to=sitio.models.upload_to_subastas),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='imagenC',
            field=models.ImageField(blank=True, null=True, upload_to=sitio.models.upload_to_subastas),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='localidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='pais',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='precioBase',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='subastas',
            name='provincia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subcategorias',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
