# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0015_auto_20170513_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorias',
            name='idCategoria',
        ),
        migrations.RemoveField(
            model_name='subastas',
            name='idSubcategoria',
        ),
        migrations.AlterField(
            model_name='subastas',
            name='idCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Categorias'),
        ),
        migrations.DeleteModel(
            name='SubCategorias',
        ),
    ]
