# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-20 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0019_auto_20170520_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='fechaAlta',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='fechaBaja',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='fechaAlta',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='fechaBaja',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
