# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0021_auto_20170520_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivosDenuncias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionMotivo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='denuncias',
            name='idMotivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.MotivosDenuncias'),
        ),
    ]
