# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0023_auto_20170525_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncias',
            name='idSubasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.Subastas'),
        ),
    ]
