# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0024_denuncias_idsubasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncias',
            name='idSubasta',
        ),
        migrations.AlterField(
            model_name='denuncias',
            name='idMotivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitio.MotivosDenuncias'),
        ),
        migrations.AlterField(
            model_name='motivosdenuncias',
            name='descripcionMotivo',
            field=models.TextField(null=True),
        ),
    ]
