# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0024_auto_20170530_2154'),
        ('sitio', '0025_auto_20170531_0032'),
    ]

    operations = [
    ]
