# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0027_denuncias_idsubasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='idUsuarioComprador',
        ),
        migrations.RemoveField(
            model_name='subastas',
            name='idCalificacion',
        ),
        migrations.DeleteModel(
            name='Calificaciones',
        ),
    ]
